<section class="aboutpage_area">
    <div class="about-img">
        <!-- <img src="<?php echo base_url(); ?>asset/new/images/about_head.jpg"></a> -->
    </div>
    <div class="about-body">
        <div class="about-left">
            <h1>Privacy Policy</h1>
            <!-- <p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">Privacy Policy</span></strong></p> -->
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">1. Introduction:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Welcome to Amar Bahok. This Privacy Policy was written to better understand how we collect, use and store your information. Since technology and privacy laws are always changing, this policy occasionally be updated. If a significant change is made, we will be sure to post a notice on our home page and in the merchant admin. If you continue to use Amar Bahok after these changes are posted, you are agreed to the revised policy. By signing up for any of the products or services offered by Amar Bahok, or dealing with a merchant using Amar Bahok Services, you are agreeing to the terms of this Privacy Policy and, as applicable, the Amar Bahok Terms of Service. This policy is a legally binding agreement between you (and your client, employer or another entity if you are acting on their behalf) as the user of the Services (referred to as &ldquo;you&rdquo; or &ldquo;your&rdquo;) and Amar Bahok. (referred to as &ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo; or &ldquo;Amar Bahok&rdquo;). If we add any new features or tools to our Services, they will also be subject to this policy. We will keep your Personal Information accurate, complete and up-to-date with the information that you provide to us. If you request access to your Personal Information, we will inform you of the existence, use and disclosure of your Personal Information as allowed by law, and provide you access to that information. When we use the term &ldquo;Personal Information&rdquo; in this policy, it means any information related to an identifiable individual, but does not include the name, title, business address, or telephone number of an employee of an organization.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">2. Information from merchants:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">If you are a merchant, you agree to post a privacy policy on your storefront that complies with the laws applicable to your business. You also agree to obtain consent from your customers for the use and access of their Personal Information by Amar Bahok and other third parties</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Information of merchants and its reason for collecting:</span></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We collect your name, company name, address, email address, phone number(s) Payment related information. We need this information to provide you with our Services, for example, to confirm your identity, contact you, and invoice you.</span></li>
    <li><span style="color:black;">We collect data about the Amar Bahok -hosted web pages that you visit and how and when you access your account, including information about the device and browser you use, your network connection and your IP address. We need this information to give you access to and improve our Services.</span></li>
    <li><span style="color:black;">We collect Personal Information about your customers that you share with us or that customers provide while shopping or during checkout.</span></li>
    <li><span style="color:black;">We use this information to provide you with our Services and so that you can process orders and serve better to your customers.</span></li>
    <li><span style="color:black;">We will also use Personal Information in other cases where you have given us express permission.&nbsp;</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Information collecting period:</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";'>
    <ol style="margin-bottom:0cm;list-style-type: circle;margin-left:17px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";'><span style="color:black;">We collect Personal Information when you sign up for our Services, when you access our Services or otherwise provide us with the information.</span></li>
    </ol>
</div>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">3. Information of customers of merchants&rsquo;:&nbsp;</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We collect our merchants&rsquo; customers&rsquo; name, email, shipping and billing address, payment details, company name, phone number, IP address and device data Where applicable.</span></li>
    <li><span style="color:black;">We need this information to provide merchants with our Services, including supporting and processing orders, authentication, and processing payments. This information is also used to improve our Services.</span></li>
    <li><span style="color:black;">Information is collected when a merchant&rsquo;s customer uses or accesses our Services, such as when a customer visits a merchant&rsquo;s site, places an order or signs up for an account on a merchant&rsquo;s site in some cases.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">4. Information from Partners:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Partners are individuals or businesses that have agreed to the terms of the Partner Program to work with Amar Bahok to promote the Services by (a) referring clients to Amar Bahok; (b) developing Amar Bahok store themes for merchant use; or (c) developing apps using the Amar Bahok Application Interface (API) for merchant use.&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Information from Partners and its reason for collecting:</span></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We collect your name, company name, website, twitter or other social media handles, phone number(s), address, business type, and email address.</span></li>
    <li><span style="color:black;">We use this information to work with you, confirm your identity, contact you and pay you.</span></li>
    <li><span style="color:black;">We collect data about the Amar Bahok -hosted web pages that you visit and how and when you access your account, including information about the device and browser you use, your network connection and your IP address. We use this information to give you access to and improve our Services.</span></li>
    <li><span style="color:black;">We collect Personal Information about your customers that you share with us or that they provide to us directly.</span></li>
    <li><span style="color:black;">We use this information to work with you and to provide our Services to your customers.</span></li>
    <li><span style="color:black;">We will also use Personal Information in other cases where you have given us express permission.&nbsp;</span></li>
    <li><span style="color:black;">We collect this information when you sign up for a Partner Account, when you sign up one of your customers for our Services, or when your customers sign up themselves. We also collect any additional information that you might provide to us.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">5. Information from Amar Bahok visitors and support users:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Information from Amar Bahok visitors and support</span><span style="color:black;">&nbsp;and its reason for collecting;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">From Amar Bahok website visitors, we collect information about the device and browser you use, your network connection and your IP address.</span></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">From telephone support users, we collect your phone number and call audio.</span></li>
    <li><span style="color:black;">From chat support users, we collect your name, email address, information about the device and browser you use, your network connection and your IP address.</span></li>
    <li><span style="color:black;">From forum users, we collect your name, email address and website URL. We use this information to service your account, enhance our Services, and answer any questions you may have.&nbsp;</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Information collecting period:</span></p>
<div style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";'>
    <ol style="margin-bottom:0cm;list-style-type: circle;margin-left:17px;">
        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:10.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";'><span style="color:black;">We collect this information when you visit Amar Bahok-hosted pages or engage with us either by email, web form, instant message, phone, or post content on our website (including forums &amp; blogs). We also collect any additional information that you might provide to us.</span></li>
    </ol>
</div>
<p style='margin-right:0cm;margin-left:27.0pt;font-size:16px;font-family:"Times New Roman","serif";margin-top:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">6. Information from cookies</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">A cookie is a small amount of data, which may include a unique identifier. Cookies are sent to your browser from a website and stored on your device. Every device that accesses our website is assigned a different cookie by us.&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">Use of cookies by Amar Bahok:</span></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We use cookies to recognize your device and provide you with a personalized experience</span></li>
    <li><span style="color:black;">We also use cookies to serve customized ads from Google and other third-party vendors.</span></li>
    <li><span style="color:black;">Our third-party advertisers use cookies to track your prior visits to our website and elsewhere on the Internet in order to serve you customized ads.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">7. Sharing of Personal Information with third parties:</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">Amar Bahok works with third parties to help provide you with our Services and we may share Personal Information with them to support these efforts. In certain limited circumstances, we may also be required by law to share information with third parties.</span></li>
    <li><span style="color:black;">Personal information may be shared with third parties to prevent, investigate, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of our Terms of Service or any other agreement related to the Services, or as otherwise required by law.</span></li>
    <li><span style="color:black;">Personal information may also be shared with a company that acquires our business, whether through merger, acquisition, bankruptcy, dissolution, reorganization, or other similar transaction or proceeding. If this happens, we will post a notice on our home page.</span></li>
    <li><span style="color:black;">Except when required by law, Amar Bahok will never disclose your Personal Information without obtaining your consent.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">8. Personal Information preservation at the time of termination relationship with us:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">We will continue to store archived copies of your Personal Information for legitimate business purposes and to comply with the law&middot; We will continue to store anonymous or anonymized information, such as website visits, without identifiers, in order to improve our Services.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">9. Personal Information safety security:</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We do not and will never share, disclose, sell, rent, or otherwise provide Personal Information to other companies for the marketing of their own products or services.</span></li>
    <li><span style="color:black;">We do not use the Personal Information we collect from you or your customers to contact or market to your customers or directly compete with you. However, AMAR BAHOK may contact or market to your customers if we obtain their information from another source, such as from the customers themselves.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">10. Way of keeping Personal Information secure:</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We follow industry standards on information security management to safeguard sensitive information, such as financial information, intellectual property, employee details and any other Personal Information entrusted to us. Our information security systems apply to people, processes and information technology systems on a risk management basis.</span></li>
    <li><span style="color:black;">No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, we cannot guarantee the absolute security of your Personal Information.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">11. Access to personal information:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">You retain all rights to your Personal Information and can access it anytime. In addition, AMAR BAHOK takes reasonable steps to allow you to correct, amend or delete personal information that is shown to be inaccurate or incomplete.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><strong><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>Data Safety Section:&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">1. Personal Information safety security:</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We do not and will never share, disclose, sell, rent, or otherwise provide Personal Information to other companies for the marketing of their own products or services.</span></li>
    <li><span style="color:black;">We do not use the Personal Information we collect from you or your customers to contact or market to your customers or directly compete with you. However, AMAR BAHOK may contact or market to your customers if we obtain their information from another source, such as from the customers themselves.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">2. Way of keeping Personal Information secure:</span></strong></p>
<ol style="list-style-type: circle;margin-left:17px;">
    <li><span style="color:black;">We follow industry standards on information security management to safeguard sensitive information, such as financial information, intellectual property, employee details and any other Personal Information entrusted to us. Our information security systems apply to people, processes and information technology systems on a risk management basis.</span></li>
    <li><span style="color:black;">No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, we cannot guarantee the absolute security of your Personal Information.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><strong><span style="color:black;">3. Access to personal information:</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;font-family:"Times New Roman","serif";margin:0cm;margin-bottom:.0001pt;text-align:justify;line-height:115%;background:white;'><span style="color:black;">You retain all rights to your Personal Information and can access it anytime. In addition, AMAR BAHOK takes reasonable steps to allow you to correct, amend or delete personal information that is shown to be inaccurate or incomplete.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><strong><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>Release Note:</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Cambria","serif";text-align:justify;'><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>&nbsp;</span></p>
<p><span style='font-size:16px;line-height:115%;font-family:"Times New Roman","serif";'>This is a fresh release/initial launched app. This is a parcel order app for Merchant side. People can order here for delivery. A Dashboard, Consignment List, Ticket List, Placement of Parcel Orders, Financial summary, payment history, Tracking and Issue Raised Options.&nbsp;</span></p>
        </div>
        <div class="about-right">
            <img src="<?php echo base_url(); ?>asset/new/images/about_person.jpg"></a>
        </div>
        <div class="clr"></div>
    </div>
</section>
<?php
    echo $this->load->view('front/layout/subscribe', [], true);
?>
